import { generateAndSendReport } from './generateMonthlyReport.js';
import { supabaseAdmin } from './supabase.js';

const ONE_HOUR_MS = 60 * 60 * 1000;
const REPORT_SCHEDULER_TIMEZONE = process.env.REPORT_SCHEDULER_TIMEZONE || 'Asia/Kolkata';
let schedulerHandle = null;

function getDateParts(now = new Date()) {
  const formatter = new Intl.DateTimeFormat('en-CA', {
    timeZone: REPORT_SCHEDULER_TIMEZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });

  const parts = Object.fromEntries(
    formatter
      .formatToParts(now)
      .filter((part) => part.type !== 'literal')
      .map((part) => [part.type, part.value])
  );

  return {
    year: parts.year,
    month: parts.month,
    day: parts.day,
  };
}

function getCurrentMonthLabel(now = new Date()) {
  const { year, month } = getDateParts(now);
  return `${year}-${month}`;
}

function isLastDayOfMonth(now = new Date()) {
  const todayParts = getDateParts(now);
  const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
  const tomorrowParts = getDateParts(tomorrow);
  return todayParts.month !== tomorrowParts.month;
}

export async function runMonthlyAutoReportJob(now = new Date()) {
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return;
  }

  if (!isLastDayOfMonth(now)) {
    return;
  }

  const month = getCurrentMonthLabel(now);

  const { data: profiles, error } = await supabaseAdmin
    .from('profiles')
    .select('id,email');

  if (error) {
    console.error('Monthly report scheduler failed to load profiles:', error);
    return;
  }

  for (const profile of profiles || []) {
    const email = String(profile?.email || '').trim();
    if (!profile?.id || !email) {
      continue;
    }

    try {
      const { data: existingReport, error: existingError } = await supabaseAdmin
        .from('user_reports')
        .select('id')
        .eq('user_id', profile.id)
        .eq('generated_for_month', month)
        .eq('is_automatic', true)
        .limit(1)
        .maybeSingle();

      if (existingError) {
        throw existingError;
      }

      if (existingReport?.id) {
        continue;
      }

      await generateAndSendReport({
        userId: profile.id,
        userEmail: email,
        month,
        sendEmail: true,
        emailToOverride: email,
        reportLabelOverride: `auto-month-${month}`,
        filtersSnapshot: {
          range: 'monthly',
          autoGenerated: true,
          month,
        },
        isAutomatic: true,
        generatedForMonth: month,
      });
    } catch (jobError) {
      console.error(`Monthly report scheduler failed for user ${profile.id}:`, jobError);
    }
  }
}

export function startMonthlyReportScheduler() {
  if (schedulerHandle) {
    return schedulerHandle;
  }

  setTimeout(() => {
    runMonthlyAutoReportJob().catch((error) => {
      console.error('Initial monthly report scheduler run failed:', error);
    });
  }, 10_000);

  schedulerHandle = setInterval(() => {
    runMonthlyAutoReportJob().catch((error) => {
      console.error('Scheduled monthly report run failed:', error);
    });
  }, ONE_HOUR_MS);

  return schedulerHandle;
}
